# Use an official Node runtime as the base image
FROM node:20

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the application
RUN npx nx run build mypoc 

# Expose the port the app runs on
EXPOSE 4200

# Set environment variables
ENV HOST 0.0.0.0
ENV PORT 4200

# Expose the port the app runs on
EXPOSE 4200

# Command to run the application in production mode
# CMD ["node", ".output/server/index.mjs"]

## development - uncomment
CMD ["npx", "nx", "run", "mypoc:serve", "--host", "0.0.0.0", "--port", "4200"]